### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by milch** [awetzel/neovim-elixir#1] opened 2015-09-02 19:29 UTC
I am trying to get this to work, but unfortunately it doesn't seem to be compatible with the current HEAD of neovim anymore. Is anyone still using/working on this project and could help me out?

**Comment by awetzel** [comment] 2015-09-05 21:16
Yes it is still maintained, but I am currently on holidays without internet. I work with last neovim release and erlang 17.3 and it works well. But I have just tried with erlang 18 and there are issues. I would be happy if you can help me. I will update the project for neovim HEAD and erlang 18 next week.

**Comment by milch** [comment] 2015-09-07 13:29
I'd love to help you get this working, unfortunately I don't know a lot about neovim plugins. 

In case it helps you, here are the Erlang, Elixir and neovim versions I am using:

```
$ erl +V 
Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 7.0.3

$ iex --version
Erlang/OTP 18 [erts-7.0.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.0.5

$ nvim --version
NVIM 0.0.0-alpha+201509070747 (compiled Sep  7 2015 15:22:53)
Commit: bb46cc2c9ce9a36f19df5c29a403c1feb4dbdf88
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150907-39318-185f9r/build/config -I/tmp/neovim20150907-39318-185f9r/src -I/tmp/neovim20150907-39318-185f9r/deps-build/usr/include -I/tmp/neovim20150907-39318-185f9r/deps-build/usr/include -I/tmp/neovim20150907-39318-185f9r/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20150907-39318-185f9r/deps-build/usr/include -I/tmp/neovim20150907-39318-185f9r/deps-build/usr/include -I/tmp/neovim20150907-39318-185f9r/deps-build/usr/include -I/tmp/neovim20150907-39318-185f9r/deps-build/usr/include -I/usr/local/opt/gettext/include -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim20150907-39318-185f9r/build/src/nvim/auto -I/tmp/neovim20150907-39318-185f9r/build/include
Compiled by manu@lyra

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

**Comment by awetzel** [comment] 2015-09-09 10:51
Thank you for the report, 

> $ iex --version
> Erlang/OTP 18

So the issue can be the same I observed when used with erlang 18.

**Comment by ianchen06** [comment] 2015-09-10 02:38
Currently the plugin throws the following error upon nvim start

```
Error detected while processing function remote#host#RegisterPlugin..remote#host#IsRunning:
line    2:
E605: Exception not caught: No host named "python3" is registered
Error detected while processing function remote#host#RegisterPlugin:
line    9:
E171: Missing :endif
Error detected while processing function remote#host#LoadRemotePlugins:
line    2:
E171: Missing :endif
```

Then :UpdateRemotePlugins throws that Erlang 17 is missing.

Thanks for such a great plugin

**Comment by milch** [comment] 2015-09-10 13:15
I believe the solution where you are overwriting a few functions in `host.vim` is also not needed anymore. Looking at the neovim source, it seems that one can now simply create a 'provider' like [these](https://github.com/neovim/neovim/tree/master/runtime/autoload/provider).

**Comment by awetzel** [comment] 2015-09-10 23:22
Ok I confirm : it works well with erlang 17 but crash with erlang 18.
I have just removed the `host.vim` overloading, and now I am investigating on the erl 18 issue.

**Comment by awetzel** [comment] 2015-09-10 23:44
I have simply recompiled the host plugin and it works now: 

```
MIX_ENV=host mix escript.build
```

So I updated it in the `nvim-rplugin` branch of `vim-elixir` plugin : https://github.com/awetzel/vim-elixir/commit/427b0dde893a7cb1470ea563648dd8f812af39c0
and it seems to work well now.

**Comment by awetzel** [comment] 2015-09-10 23:48
So I think it is OK, if you can confirm that on your side it works now, it would be helpful, thank you very much.

**Comment by milch** [comment] 2015-09-29 14:40
Sorry for not coming back to you earlier, but I just tried updating to your branch of `vim-elixir`, this is now the error I get:

<img width="952" alt="screen shot 2015-09-29 at 16 35 16" src="https://cloud.githubusercontent.com/assets/279407/10167411/b2aeb37a-66c8-11e5-955c-cdc2f5ef3668.png">

As you know from my previous descriptions, I have Erlang 18 installed.

**Comment by ghost** [comment] 2015-11-21 16:43
Neovim's configuration settings were recently changed (https://github.com/neovim/neovim/issues/78) I've been having problems getting this plugin working and was wondering if anyone has had luck fixing and/or getting this to work.

**Comment by awetzel** [comment] 2015-11-21 18:03
I am using it on daily basis with last neovim version without any issues, could you please be more specific about how you "installed" it ?

Actually it should not depend on XDG paths or on any path since the executable is searched with : `globpath(&rtp, 'tools/nvim_elixir_host')`. So the only needed things to have it working are : 
- `tools/nvim_elixir_host` in one of your nvim runtime paths, the executable `nvim_elixir_host` being built with `MIX_ENV=host mix escript.build`
- `plugin/elixir_host.vim` in one of your nvim runtime paths, this file is in the neovim-elixir repo
- some Elixir plugin file inside a `rplugin/elixir` directory in one of your runtime paths. For instance use https://github.com/awetzel/vim-elixir/blob/nvim-rplugin/rplugin/elixir/elixir_plugin.ex
  this plugin file will add : 
  - `:ElixirExec` command, which Execute the selected Elixir lines or whole file, keeping binding across execution, :ElixirExec! with bang will reset bindings
  - `:MixStart` `:MixStop` commands will start or stop the current Mix project inside your vim plugin
  - `:MixLoad` will change the Mix project taking the closest parent mix.exs relative to current buffer file
  - `ElixirComplete` function, use `setlocal omnifunc=ElixirComplete` to use it for omnicompletion with module, spec and function documentations
- update the "rplugin" registry with `:UpdateRemotePlugins` 

Sometimes depending on the version of Erlang running it, I have to rebuild the Elixir host doing : 

```
mix deps.get
MIX_ENV=host mix escript.build
```

Then `cp vim-elixir-host/tools/nvim_elixir_host path/to/nvim/tools/nvim_elixir_host` to use the newly built plugin.

**Comment by ghost** [comment] 2015-11-21 19:53
My first naive attempt was just using vim-plug as such
`Plug 'awetzel/vim-elixir', {'for': 'elixir',  'branch': 'nvim-rplugin'}` which gave me `Unknown function: ElixirComplete` when trying to `<C-x><C-O>` complete in a .ex file, then I tried installing the vim-elixir plugin manually and then tried compiling this project as described in the readme. 

When I manually copied the fork of vim-elixir, using these instructions (modified to use `.config/nvim` instead of `.nvim`)

```
git clone -b nvim-rplugin https://github.com/awetzel/vim-elixir
cp -R vim-elixir/* ~/.config/nvim/
```

Then the process hangs up on calling `UpdateRemotePlugins`

When I manually compiled using these instructions 

```
# clone the project and cd into it...
mix deps.get
MIX_ENV=host mix escript.build
cp -R vim-elixir-host/* ~/.config/nvim
```

and then copying this file [https://github.com/awetzel/vim-elixir/blob/nvim-rplugin/rplugin/elixir/elixir_plugin.ex](https://github.com/awetzel/vim-elixir/blob/nvim-rplugin/rplugin/elixir/elixir_plugin.ex) to `~/.config/nvim/rplugin/elixir/completion.ex` I get this error when I try to run `UpdateRemotePlugins

```
Error detected while processing function <SNR>19_UpdateRemotePlugins..<SNR>19_RegistrationCommands:
line   16:
Channel was closed by the client
remote/host: elixir host registered plugins ['completion.ex']
```

And none of the functions (`ElixirComplete`, etc.`) are available. 

Not really sure where to go from here.

**Comment by ghost** [comment] 2015-11-21 20:09
I also tried the 

> ```
> mix deps.get
> MIX_ENV=host mix escript.build
> ```
> 
> Then cp vim-elixir-host/tools/nvim_elixir_host path/to/nvim/tools/nvim_elixir_host to use the newly built > plugin.

solution which gave me the same `Channel was closed by the client` error. Also I have Erlang/OTP 18 and Elixir 1.1.1 if that is something that could break it. I also have installed  a fresh copy of neovim from source.

**Comment by awetzel** [comment] 2015-11-21 20:45
Ok the only thing I see is that when you tried to install it with `vim-plug` you forgot to do the `:UpdateRemotePlugin`, that is why you have "Unknown function: ElixirComplete".

But since your other attempts failed as well, the problem is elsewhere.

I have just rebuilt mine from scratch with Erlang 18.0 and Elixir 1.1.0 and nvim from 15/09/2015 and that works well.

I will try to update to the nvim HEAD and 1.1.1 to see if I get a new problem.

One other thing is weird, when you get "remote/host: elixir host registered plugins ['completion.ex']", all seems to be OK, are you sure you do not have another host plugin which crashes ?
To verify if the registration worked, look at the file `~/..nvimrc-rplugin~` if there is such file and it contains : 

```
call remote#host#RegisterPlugin('elixir', '/Users/kbrw/.nvim/bundle/vim-elixir/rplugin/elixir/elixir_plugin.ex', [
      \ {'sync': 1, 'name': 'ElixirComplete', 'opts': {'eval': '[col(''.''),getline(''.'')]'}, 'type': 'function'},
      \ {'sync': 1, 'name': 'ElixirExec', 'opts': {'bang': '', 'range': '%'}, 'type': 'command'},
      \ {'sync': 0, 'name': 'MixLoad', 'opts': {'eval': '[expand(''%:p:h'')]'}, 'type': 'command'},
      \ {'sync': 0, 'name': 'MixStart', 'opts': {'nargs': '*'}, 'type': 'command'},
      \ {'sync': 0, 'name': 'MixStop', 'opts': {'nargs': '*'}, 'type': 'command'},
     \ ])
```

then the registration worked and the host plugin also worked (since the registration process use the host plugin to communicate function and command specifications to vim).

**Comment by awetzel** [comment] 2015-11-21 23:54
Hello again, I had issues to install the HEAD of nvim due to MacOs compilation problems, so I finally get the last neovim in a Debian VM last neovim and experiencing issues with the host plugin :) so I might be able to fix it.

**Comment by dm1try** [comment] 2015-12-03 10:33
@awetzel any news? maybe you need some help or additional info? :)

**Comment by awetzel** [comment] 2015-12-03 20:59
hello dm1try,
Actually I have unfortunately met the bug with the last Nvim, and without the plugin I have a huge productivity loss in my Elixir dev so I am pretty in a hurry to fix the problem.
But currently I am putting a big project into production and do not have time to fix it, maybe at the end of next week.

**Comment by dm1try** [comment] 2015-12-04 03:37
@awetzel thanks
I fixed my problem, see [the PR](https://github.com/awetzel/neovim-elixir/pull/2).
![screenshot](https://cloud.githubusercontent.com/assets/486807/11581088/4b615eec-9a4f-11e5-8d35-650b350bb3b5.png)
As for me the main problem atm, it's a hard debugging/developing a plugins with such infastructure
- lack of tests
- no logs for the host application(I know STDIN/OUT are piped, but we can write on a disk)
  there is "log proxy" but it doesn't help if nvim and host hang up together.

Also it would be good move to split host and client to different projects(?)
The last, different providers for different Elixir versions will help too :)

**Comment by awetzel** [comment] 2015-12-05 23:47
Thank you for your time and your debugging.
About the tests, since it is a plugin for nvim the most important/relevant test is the compatibility with last nvim version: connection and "nvim specification format" for the `:UpdateRemotePlugins`.

Unfortunately I tried on september (when the issue was opened) and did not find any way to do that kind of testing with travis :( .

For the logging thing, yes, I think a 10 LOC File Backend for Logger would be nice with comments on the confix.exs for debugging.

Then I think it would be nice to have one branch of `vim-elixir` containing the Host per Erlang version to ensure compatibility with your version.

About a different project for host and client I am not sure exactly what you mean since the only addition to make the client a host are : 

https://github.com/awetzel/neovim-elixir/blob/master/lib/link.ex#L110
https://github.com/awetzel/neovim-elixir/blob/master/mix.exs#L24-L28
the config and
https://github.com/awetzel/neovim-elixir/blob/master/lib/app.ex#L47-L52
for the client `attach` task to config `:link` according to task param.

**Comment by dm1try** [comment] 2015-12-06 06:44
Sure, no problem :)

> About the tests, since it is a plugin for nvim the most important/relevant test is the compatibility with last nvim version: connection and "nvim specification format" for the :UpdateRemotePlugins.

I agree, the integration testing is important here. Also some functional tests for the main modules can help new developers. I mostly use [`espec` framework](https://github.com/antonmi/espec). So I can try to help but if I can use it for this :)

> For the logging thing, yes, I think a 10 LOC File Backend for Logger would be nice with comments on the confix.exs for debugging.
> Then I think it would be nice to have one branch of vim-elixir containing the Host per Erlang version to ensure compatibility with your version.

:+1: 

> About a different project for host and client I am not sure exactly what you mean since the only addition to make the client a host are :

Ok, thanks for the clarifying this. I've noticed the "smell" - `MIX_ENV=host` it seems like the env var is used for make the difference between apps but not the difference between environments. 
I thought that client responsibilities: connect to nvim,retrieve the nvim API/provide an interface to call this API; host responsibilities: make a bridge between Elixir plugins and nvim(load the plugins/translate their interfaces to nvim compatible and return them by a request, allow to use the client API inside plugins). 
Anyway, I've realized that the different projects is overhead here!

But I have another proposals :) (btw, we should close this issue and continue in other tread, it's the last message :smile:  )
I updated the autocomplete script with project-depended autocompletion(inspired by [alchemist-server](https://github.com/tonini/alchemist.el/blob/master/alchemist-server/lib/server.exs)) and bunch of small tweaks: show the first sentence/autoclose the doc-preview window then I go to the next line/etc..
![screenshot](https://cloud.githubusercontent.com/assets/486807/11611935/c79ab77c-9bf5-11e5-97c7-2828b4178b92.png)
![scr](https://cloud.githubusercontent.com/assets/486807/11611937/cc093d1a-9bf5-11e5-984b-2743cebe9c78.png)

I also will add smart refactoring tools to this "script". I write this stuff using usual flow(tests/many levels of abstraction :grin: and so on). And I wanna share this with community. So gists will not work here. But the `mix` already solves this.
The proposal is the adding to `neovim-elixir` framework-like(AKA `fluid` :smile:) responsibilities:
- easy installing 
  `
  mix archive.install ../neovim-elixir-0.1.1.ez, neovim_elixir.install_host
  `
- installing community plugins(as usual packages?)

As a result of this `neovim-elixir` can be able to process usual dynamically loaded `Elixir` scripts and community packaged plugins(a host must be recompiled).

Don't get me wrong, I don't wanna make things complicated. As for me it's just some way to go.
You've already solved most non-trivial problems(thanks!) but there is still room for ​improvement :bowtie:

My priority for all those proposals: 
- HIGH  developer/debug environment
  - the logging
  - integration tests and helpers for a testing
  - docs(how to use NVim interface)
- MID a framework-like feature described above
- very LOW support different elixir versions

**Closed as completed** 2015-12-06 17:35 UTC
